### ISSUE TITLE
AttributeError: module 'snntorch' has no attribute 'spikegen'

### ISSUE THREAD

**Issue by sambaPython24** [jeshraghian/snntorch#109]
* snntorch version:     0.5.1
* Python version:      3.7
* Operating System:   Windows

### Description
When I try to reproduce one of the example, e.g. 
```
import snntorch as snn

a = torch.Tensor([1, 2, 2.9, 3, 3.9])
snn.spikegen.delta(a, threshold=1)
```
I get the error ```module 'snntorch' has no attribute 'spikegen'```. Where do I find the module?

**Comment by jeshraghian** [comment]
Have you imported spikegen?

`from snntorch import spikegen`
