### ISSUE TITLE
Minor Update to Dependencies list in README.rst

### ISSUE THREAD

**Issue by katywarr** [jeshraghian/snntorch#128]
* snntorch version: 0.5.3
* Python version: 3.10.4
* Operating System: Windows 10

### Description

I think that `ffmpeg` is missing from the dependencies listed in `README.rst`.

### What I Did

Using conda, I installed the dependencies and then received the following error on the video conversion step of the first tutorial:
```
RuntimeError: Requested MovieWriter (ffmpeg) not available
```
This was easily sorted with: `conda install -c conda-forge ffmpeg`.

**Comment by jeshraghian** [comment]
Thanks for catching this! 

I consider the 'animation saving' / 'compression to mp4' to be something that can interface with snntorch rather than something that is part of snntorch. So it might be best to include it in the tutorial rather than the dependencies. 

To keep it consistent with the tutorials, let's install via PyPi rather than conda. 
We can add it in the relevant section as a commented code-block: `#!pip install ffmpeg`. 

Feel free to apply the change to the notebook and push directly to the master branch, otherwise I'll try to handle it sometime this week.

**Comment by katywarr** [comment]
Yes, that's a nicer fix than updating the dependency list as it's just a function that's being used in the tutorial. I'll do the change as suggested later today.

**Comment by katywarr** [comment]
I took a look but unfortunately it's looking more complicated.

I cleaned my environment to uninstalled `ffmpeg` and then re-installed it from within the notebook using `!pip install ffmpeg` as suggested. It appeared to be successful:

```
Collecting ffmpeg
  Using cached ffmpeg-1.4-py3-none-any.whl
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4
```

Unfortunately, the animation step still produced the initial error (as if ffmpeg was not installed). Subsequent attempt to re-install (just in case!) gave:

```
Requirement already satisfied: ffmpeg in c:\users\katyw\anaconda3\envs\snntorch\lib\site-packages (1.4)
```

I then uncommented the line above the animation step and to set `animation.ffmpeg_path` to the location of the exe installation:

```
plt.rcParams['animation.ffmpeg_path'] = 'c:\\users\\katyw\\Anaconda3\\pkgs\\ffmpeg-5.1.0-gpl_h36dc936_101\\Library\\bin\\ffmpeg.exe'
```

Now the exe was found but its DLLs were not:
```
ffmpeg.exe - System Error
The code execution cannot proceed because fontconfig-1.dll was not found. Reinstalling the program may fix this problem.
```

I suspect this is because the pip install does not copy the dlls into the `sys.path` dll location being used by the conda environment (so the DLLs for the exe can't be found).

Just to check, I re-ran the conda install outside the notebook and it worked fine (without the `animation.ffmpeg_path` needing to be set) because conda install also copied the dlls to the approprate folder.

I'm really not sure what this best fix here is as I agree that ideally it would be nicer to have this in the app and not a special case for conda. I haven't tried to see whether the `pip install` works within the notebook in a non-conda environment.  Any thoughts?

**Comment by jeshraghian** [comment]
I find that the non-conda Google Colab environment doesn't require ffmpeg to be installed, so I think the best approach would be to add the suggestions in markdown. 

Perhaps we can change the following note:

"_Note: if you are running the notebook locally on your desktop, please uncomment the line below and modify the path to your ffmpeg.exe_"

to:

"_Note: if you are running the notebook locally, please uncomment the line below and modify the path to your ffmpeg.exe. This may require you to install ffmpeg: e.g., `pip install ffmpeg` or if in a Conda environment, `conda install -c conda-forge ffmpeg`_"

Would you like to update the notebook & I can update the static webpage on readthedocs?

**Comment by jeshraghian** [comment]
Sounds good to me! I made a tiny adjustment. Please go ahead with the
following:

"Note: if you are running the notebook locally you may need to install
ffmpeg: e.g., pip install ffmpeg or if in a Conda environment, conda
install -c conda-forge ffmpeg.
If ffmpeg is not found, please uncomment the line below and modify the path
to your ffmpeg.exe."
