### ISSUE TITLE
Tutorial 7 - event_tensor shape is unmatched 

### ISSUE THREAD

**Issue by msjun23** [jeshraghian/snntorch#133]
* snntorch version: 0.5.3
* Python version:   3.8.10
* Operating System: Ubuntu 20.04

### Description

At "Tutorial 7 - NEUROMORPHIC DATASETS WITH TONIC + SNNTORCH", shape of event_tensor, made by torch.utils.data.DataLoader, is depicted as **torch.Size([311, 128, 2, 34, 34])**. But when I run the codes, shape of event_tensor shown as **torch.Size([128, 311, 2, 34, 34])**, first and second dimensions are changed. So I couldn't train anything, because tensor shape is not matched exactly.

Why does the shape of tutorial look different from the actual implementation?

Was there any update of snnTorch or torch(DataLoader)?

### What I Did

Here is colab error message. I didn't modify anything, just ran tutorial code.

```
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:530: UserWarning: Using a target size (torch.Size([128, 10])) that is different to the input size (torch.Size([312, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-18-5a0ce5857296>](https://localhost:8080/#) in <module>
     13         net.train()
     14         spk_rec = forward_pass(net, data)
---> 15         loss_val = loss_fn(spk_rec, targets)
     16 
     17         # Gradient calculation + weight update

4 frames
[/usr/local/lib/python3.7/dist-packages/torch/functional.py](https://localhost:8080/#) in broadcast_tensors(*tensors)
     71     if has_torch_function(tensors):
     72         return handle_torch_function(broadcast_tensors, tensors, *tensors)
---> 73     return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
     74 
     75 

RuntimeError: The size of tensor a (312) must match the size of tensor b (128) at non-singleton dimension 0
```

**Comment by msjun23** [comment]
When you update docs, plz command here.

I just solve this problem with ```data = data.transpose(0,1)```, at function: forward_pass(), but I want to know what was problem, and this solution could be or not the answer.

**Comment by jeshraghian** [comment]
Thanks for flagging this - I finally got around to fixing it. 

Tonic switched the batch and time dimensions in a recent release. 
Transposing is a good solution, though I used the `batch_first=False` argument below instead:

`testloader = DataLoader(cached_testset, batch_size=batch_size, collate_fn=tonic.collation.PadTensors(batch_first=False))`
