### ISSUE TITLE
Snntorch tutorials 

### ISSUE THREAD

**Issue by Aliyulmusa** [jeshraghian/snntorch#134]

**Comment by jeshraghian** [comment]
So is there an issue?

**Comment by Aliyulmusa** [comment]
No, I'm sorry Prof. I was trying to clone the tutorials into my
github account, I don't know how I logged an issue. Sorry for that, Sir.
How are you doing Prof. I'm an MSc. student in Computer Engineering from
Nigeria, and new to the field neuroscience and AI, I found snntorch
tutorials useful and highly interested, I'm planning to use it in my MSc.
research.
Sir, is it possible to use snntorch on medical image classification? Like
brain tumor detection and classification. I'm beginner in machine learning
as I said.

**Comment by Aliyulmusa** [comment]
Glad to meet you, Sir. Thank you
