### ISSUE TITLE
How to install Popular SDK

### ISSUE THREAD

**Issue by sungjae-cho** [jeshraghian/snntorch#136]
* snntorch version: Not needed
* Python version: Not needed
* Operating System: Not needed

### Description

I would like to install snntorch. I found it requires poptorch, which is dependent on Popular SDK.
How can I download  Popular SDK? GraphCore offers Popular SDK only for signed-up users.
For this reason, I cannot download Popular SDK... Please help me.

**Comment by vinniesun** [comment]
Hi Sungjae,

snnTorch have two package available on pypi, the normal snnTorch and snnTorch-IPU.

If you want to use the normal snnTorch, use the following command to install:
```
pip install snntorch
```

For the snnTorch-IPU version, use the following command to install:
```
pip install snntorch-ipu
```

The Poplar SDK is only required if you are using snnTorch with Graphcore's IPU.

**Comment by sungjae-cho** [comment]
@vinniesun Thanks, Vincent. I thought it was necessary to install `snntorch-ipu` and this package does not wrap the original  `snntorch`. I have just run `pip uninstall snntorch-ipu` and solved the problem.
