### ISSUE TITLE
snntorch-ipu crashing

### ISSUE THREAD

**Issue by RoelMK** [jeshraghian/snntorch#153]
* snntorch version: 0.5.3
* snntorch-ipu version: 0.5.18
* PopTorch version: 2.6.0
* PyTorch version: 1.10.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description

I've been trying to train a model in an IPU environment using PopTorch and snntorch-ipu. Unfortunately, I always get a crash. It is unclear to me what exactly is going on, so hopefully someone knows.

### What I Did

If I try to train my model with only snntorch-ipu installed, as recommended, I will always get an error message when importing/working with surrogates about "Missing Straight Through Estimator Custom Operation file".

```
/notebooks/dvsclf/network/net.py in <module>
      1 import torch
----> 2 from snntorch import surrogate
      3 from snntorch import utils
      4 import torch.nn as nn
      5 import numpy as np

/usr/local/lib/python3.8/dist-packages/snntorch/surrogate.py in <module>
     26 
     27 
---> 28 class StraightThroughEstimator:
     29     """
     30     Straight Through Estimator.

/usr/local/lib/python3.8/dist-packages/snntorch/surrogate.py in StraightThroughEstimator()
     53         print("Missing Straight Through Estimator Custom Operation file!")
     54         print(so_path_ste)
---> 55         exit(1)
     56     ctypes.cdll.LoadLibrary(so_path_ste)
     57 

NameError: name 'exit' is not defined
```

If I install snntorch (with or without snntorch-ipu beside it), I will not get the above error. Instead, something in PopTorch throws an error when the model is being trained.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-9ee252bfabe9> in <module>
      2     # Performs forward pass, loss function evaluation,
      3     # backward pass and weight update in one go on the device.
----> 4     _, loss = poptorch_model(batch, target)

[....]

/notebooks/dvsclf/network/snn.py in forward(self, x)
     20 
     21         x = self.conv(x)
---> 22         x = self.lif(x)
     23         return x
     24 

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1118             input = bw_hook.setup_input_hook(input)
   1119 
-> 1120         result = forward_call(*input, **kwargs)
   1121         if _global_forward_hooks or self._forward_hooks:
   1122             for hook in (*_global_forward_hooks.values(), *self._forward_hooks.values()):

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
   1088                 recording_scopes = False
   1089         try:
-> 1090             result = self.forward(*input, **kwargs)
   1091         finally:
   1092             if recording_scopes:

/usr/local/lib/python3.8/dist-packages/snntorch/_neurons/leaky.py in forward(self, input_, mem)
    159         if self.init_hidden:
    160             self._leaky_forward_cases(mem)
--> 161             self.reset = self.mem_reset(self.mem)
    162             self.mem = self.state_fn(input_)
    163 

/usr/local/lib/python3.8/dist-packages/snntorch/_neurons/neurons.py in mem_reset(self, mem)
     86         """Generates detached reset signal if mem > threshold.
     87         Returns reset."""
---> 88         mem_shift = mem - self.threshold
     89         reset = self.spike_grad(mem_shift).clone().detach()
     90 

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in __torch_function__(cls, func, types, args, kwargs)
    279                     if kwargs is None:
    280                         kwargs = {}
--> 281                     return super().__torch_function__(func, types, args,
    282                                                       kwargs)
    283 

RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
(1,1,.,.) = 
 Columns 1 to 9  0.4529  0.4529  0.4529  0.4529  0.4529  0.4529  0.4529  0.4529  0.4529 ....
```

With `self.lif =  snn.Leaky(beta=0.95, spike_grad=surrogate.fast_sigmoid(), init_hidden=True, learn_beta=True, learn_threshold=True)`

**Comment by jeshraghian** [comment]
Thanks for flagging this. Tagging @vinniesun who may also be familiar.

A few features have not yet made it into the IPU release. 
Are you able to disable `init_hidden=True`?

This means you might need to follow the procedure for developing models from the [IPU tutorial here.](https://snntorch.readthedocs.io/en/latest/tutorials/tutorial_ipu_1.html) 

If it still isn't working, try disabling `learn_beta=True` and `learn_threshold=True` as well.

**Comment by vinniesun** [comment]
@RoelMK can you share the code for the model you are working with atm (snnTorch-ipu version)? This will make it easier for us to get a better idea for why your code is crashing

**Comment by RoelMK** [comment]
Unfortunately, my IPU environment broke down, so I have not been able to test what @jeshraghian suggested. When it is up again and I have tested the changes, I will let you know. 
For the model, I am using an adjusted and simplified version of DenseNet. Below you can find my implementation of a dense layer (already adjusted such that `init_hidden=False`), which seems to be involved in the RuntimeError. I am using snnTorch-ipu version 0.5.18.
```py
class DenseLayer(nn.Module):
    def __init__(self, in_channels, out_channels, spike_grad, beta):
        super(DenseLayer, self).__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
        self.lif = snn.Leaky(beta=beta, spike_grad=spike_grad, learn_beta=True, learn_threshold=True)
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.reset()

    def reset(self):
        self.lif_mem = self.lif.init_leaky()

    def forward(self, x):
        """
        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, in_channels, height, width)
        Returns:
            torch.Tensor: Output tensor of shape (batch_size, out_channels, height, width)
        """

        x = self.conv(x)
        x, self.lif_mem = self.lif(x, self.lif_mem)
        return x
```

**Comment by RoelMK** [comment]
I have tested the changes @jeshraghian suggested. With `init_hidden=False`, inference seems to work, but training still does not. Setting `learn_beta=False` and/or `learn_threshold=False` does not make a difference. The following error is thrown.
```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-8-9ee252bfabe9> in <module>
      2     # Performs forward pass, loss function evaluation,
      3     # backward pass and weight update in one go on the device.
----> 4     _, loss = poptorch_model(batch, target)

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in __call__(self, *args, **kwargs)
    938 
    939         if not self.isCompiled():
--> 940             self._compile(in_tensors)
    941 
    942         if not self._is_attached:

/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py in wrapper(self, *args, **kwargs)
    286         def wrapper(self, *args, **kwargs):
    287             with self._profiling.tracepoint(label):  # pylint: disable=protected-access
--> 288                 return func(self, *args, **kwargs)
    289 
    290         return wrapper

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in _compile(self, in_tensors)
    661         if not self.isCompiled():
    662             if self._options.Jit.trace_model:
--> 663                 self._executable = poptorch_core.compileWithTrace(*trace_args)
    664             else:
    665                 self._executable = self._compileWithDispatch(

Error: In poptorch/source/LowerToPopart.cpp:913: 'poptorch_cpp_error': Couldn't find a registered operation for node %3207 : Float(96, 8, 34, 34, strides=[9248, 1156, 34, 1], requires_grad=1, device=cpu) = ^ATan(2.0)(%38904), scope: __module.model/__module.model.classifier/__module.model.classifier.snn_net/__module.model.classifier.snn_net.denseblocks.0/__module.model.classifier.snn_net.denseblocks.0.layers.0/__module.model.classifier.snn_net.denseblocks.0.layers.0.lif # /usr/local/lib/python3.8/dist-packages/snntorch/surrogate.py:202:0

Error raised in:
  [0] processing %3207 : Float(96, 8, 34, 34, strides=[9248, 1156, 34, 1], requires_grad=1, device=cpu) = ^ATan(2.0)(%38904) # /usr/local/lib/python3.8/dist-packages/snntorch/surrogate.py:202:0
  [1] LowerToPopartImpl::lowerBody
  [2] compileWithTrace
```

A similar error is thrown for different surrogates (tested ATan, Sigmoid and Straight Through Estimator). Note that this is with the latest version of both snnTorch and snnTorch-ipu installed. If only snnTorch-ipu is installed, surrogates do not work at all (cannot import as shown in opening post).

**Comment by jeshraghian** [comment]
Hmm thanks for testing both cases

Snntorch should definitely be uninstalled, with only snntorch-ipu installed (perhaps from scratch as there are a few custom objects compiled automatically on installation). If snntorch was installed at the time of snntorch-ipu installation, there is a chance there is a clash with the directory these files are compiled in.

Once that is done, we have only implemented surrogate functions for the straight through estimator and fast sigmoid functions so far - try testing those for now with the fresh installs. 

Let me know how that goes; possibly let me know if you're able to run the Python script from the IPU tutorial on MNIST too. 

That can tell us if it's an environment problem or code problem.

**Comment by RoelMK** [comment]
When I try to run the IPU tutorial with (only) the latest version of snntorch-ipu installed, l get the following error (running https://github.com/jeshraghian/snntorch/blob/master/examples/tutorial_ipu_1.py).
```
Missing so files, will compile them now!
Successfully created!
Missing Straight Through Estimator Custom Operation file!
/usr/local/lib/python3.8/dist-packages/snntorch/so_file/straight_through_estimator_custom_ops.so
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-1c6c254807c7> in <module>
     12 import snntorch as snn
     13 from snntorch.functional import loss as SF
---> 14 from snntorch import surrogate
     15 from snntorch import spikegen
     16 

/usr/local/lib/python3.8/dist-packages/snntorch/surrogate.py in <module>
     26 
     27 
---> 28 class StraightThroughEstimator:
     29     """
     30     Straight Through Estimator.

/usr/local/lib/python3.8/dist-packages/snntorch/surrogate.py in StraightThroughEstimator()
     53         print("Missing Straight Through Estimator Custom Operation file!")
     54         print(so_path_ste)
---> 55         exit(1)
     56     ctypes.cdll.LoadLibrary(so_path_ste)
     57 

NameError: name 'exit' is not defined
```

**Comment by vinniesun** [comment]
@RoelMK thanks for this bug report. Can you please verify that the shared object file "straight_through_estimator_custom_ops.so" was not built?
Please go to the path "/usr/local/lib/python3.8/dist-packages/snntorch/so_file/" and see what shared object file(s) are there. Based on what you shared, the shared object files should've been compiled and created.

**Comment by RoelMK** [comment]
The /usr/local/lib/python3.8/dist-packages/snntorch/so_file folder does not contain any .so files. Only a file "__init__.py" and a folder  "__pycache__".

**Comment by jeshraghian** [comment]
Thanks for letting us know.

@vinniesun - I think that the easiest fix will be to install from git, and compiling the .so files manually with a couple of lines rather than trusting pip to automatically do it. I'll let you know once graphcore have approved access again + we can update the install instructions.

We'lll keep you posted here.

**Comment by vinniesun** [comment]
@RoelMK I have found the issue that's causing the shared objects files not compiling. The Popart API have a new library that need to be included.

Can you please do the following as a quick fix.

In Terminal, enter the add the following line 
```
#include <popart/popx/opx.hpp>
```
to the following files:
* /usr/local/lib/python3.8/dist-packages/snntorch/custom_ops/fast_sigmoid.cpp
* /usr/local/lib/python3.8/dist-packages/snntorch/custom_ops/heaviside_custom_op.cpp
* /usr/local/lib/python3.8/dist-packages/snntorch/custom_ops/straight_through_estimator.cpp

Then you should be able to generate the shared object files.

![image](https://user-images.githubusercontent.com/5231458/207764846-b6ee4268-2ed6-470a-9151-f972126a359f.png)

We will be pushing the update to pypi soon, at the moment I'm out of office.

**Comment by RoelMK** [comment]
It is working now. Thank you for your help!
