### ISSUE TITLE
TBPTT mode gives error about K parameter on time varying data

### ISSUE THREAD

**Issue by alisam1992** [jeshraghian/snntorch#172]
* snntorch version: 0.5.3
* Python version: 3.8
* Operating System: windows

when i try to use TBPTT or RTRL from backprop on time varying signal, it gives me this error:

[Java Printing.pdf](https://github.com/jeshraghian/snntorch/files/10328886/Java.Printing.pdf)

```
    if K_flag is False:
UnboundLocalError: local variable 'K_flag' referenced before assignment
```

**Comment by jeshraghian** [comment]
Unfortunately the `backprop` module will be deprecated from the next version as it's a lot less inefficient than manually putting together a training loop.

As such, I recommend building a model in a separate class where the forward function simulates one single time-step for training.

Then perform the `model.backward()` update every `K` steps manually. 
Following each update, the state variables should be detached from the computational graph to avoid backpropagating through them again: e.g., `mem.detach_()`

If you run into errors using a manual implementation of TBPTT, then feel free to raise another issue.

**Comment by alisam1992** [comment]
Dear Jason

thanks for your reply. just one question:
can the detachment be done by *utils.reset(net)* ? (regarding
*mem.detach_()*)

**Comment by jeshraghian** [comment]
That will work if youre using the argument `init_hidden=True`, and will otherwise require manual detaching.

**Comment by alisam1992** [comment]
Awesome thanks man
