### ISSUE TITLE
Boosting methods in snnTorch

### ISSUE THREAD

**Issue by kgano-ucsd** [jeshraghian/snntorch#185]
Hi,

I'd like to ensemble a few SNNs together to see if I can squeeze out some more performance. Is there a recommended way to do this? If not, it'd be awesome if you could support PyTorch-Ensemble - I have tried, but it seems like there may be some core compatibility issues getting the snnTorch model to work with the library.

**Comment by jeshraghian** [comment]
I've never played with PyTorch Ensemble, though this sounds cool.
Could you share a code-snippet / the error?
It'd be good to get a better idea of what the error stems from; whether it's from snnTorch's side or if it's better optimized from PyTorch-Ensemble.

**Comment by kgano-ucsd** [comment]
Sure thing!

Code that sets all inputs to same dtype:
```
dtype = torch.float
X_train = torch.tensor(X_train_fps, device=device, dtype=dtype)
X_test = torch.tensor(X_test_fps, device=device, dtype=dtype)
y_train = torch.tensor(y_train_fps, device=device,dtype=dtype)
y_test = torch.tensor(y_test_fps, device=device,dtype=dtype)

train_data = TensorDataset(X_train, y_train)
test_data = TensorDataset(X_test, y_test)

# Create DataLoaders
train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True, drop_last=True)
test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=True, drop_last=True)
```

Model architecture is pretty simple, nothing more than the sample network from Tutorial 5.

I pulled the ensemble code from the PyTorch-Ensemble examples:
```
model = GradientBoostingClassifier(
    estimator=SNN,
    n_estimators=10,
    cuda=False, # I have a macbook so no CUDA for me :(
)

# Set the criterion
criterion = nn.CrossEntropyLoss()
model.set_criterion(criterion)

# Set the optimizer
model.set_optimizer('Adam', lr=1e-3, weight_decay=5e-4)

# Train and Evaluate
model.fit(
    train_loader,
    epochs=50,
    test_loader=test_loader
)
```

And finally, the error:

![image](https://user-images.githubusercontent.com/103277185/216520693-2ade219f-f50b-42ad-a277-d43d55a2da50.png)

When I change dtype for my inputs to be torch.int64, I get this:

![image](https://user-images.githubusercontent.com/103277185/216520897-c0db8ed2-18c7-4b2f-a0cb-aa58aaf04ddc.png)

**Comment by jeshraghian** [comment]
The membrane potential of the neuron initializes as `dtype = torch.float`. 

Options: 

1) modify PyTorch Ensemble so that it is compatible with floats.
2) modify snnTorch so it is compatible with `torch.long` / int64

Re: 2; I'm not sure if it'll work, but are you able to test cloning the repo, and modifying every instance of `dtype` to be an integer? I haven't had much experience with training with fixed precision variables.

**Comment by jeshraghian** [comment]
Closing due to the inactivity.
