### ISSUE TITLE
approximate the power consumption by conting the number of spikes

### ISSUE THREAD

**Issue by oshima-yoppi** [jeshraghian/snntorch#189]
Hi!
Thanks for publishing this excellent program.
I would like to count the number of spikes in order to approximate the power consumption. How can I do this?

**Comment by jeshraghian** [comment]
The tutorial show how to recording spikes into lists:

```
spk_rec = []
spk_rec.append(spk)
spk_rec = torch.stack(spk_rec)
```

You would then just sum the spk_rec variable (possibly multiple times depending on shape):

`spk_rec.sum()`

Keep in mind - spike count alone won't give a reliable estimate of power consumption.
You will want to measure the total number of operations, as one spike will be broadcast to many weights when transmitted between layers.
