### ISSUE TITLE
snnTorch tutorial and docs update: matching tutorials to codes

### ISSUE THREAD

**Issue by jeshraghian** [jeshraghian/snntorch#196]
There are a few mismatches between the LIF neuron and the explanations / figures in the tutorials.

* Tutorial 3 eqn 11 needs fixing
* Tutorial 5 figures should be matched, or at least a note that mentions what connections have been omitted
* Add a note to mention a lot of this is empirical. The precise graphs don't matter too much. They're all slight variations of LIF neurons. It's just that we found some to be a little faster or better in accuracy. We have no idea why they work well, they just do. It's important that people know this.

Feel free to add any other nitpicks in comments below.

**Comment by HeMuling** [comment]
Tutorial 2 part 3 Lapicque's LIF Neuron Model, the link to the pdf is dead

```
This similarity between nerve membranes and RC circuits was observed by [Louis Lapicque in 1907](https://core.ac.uk/download/pdf/21172797.pdf).
```

**Comment by jeshraghian** [comment]
Thanks for catching that @HeMuling - all fixed now!
