### ISSUE TITLE
Potential Issue with version 0.6.1's fix for M1 GPU compatibility.

### ISSUE THREAD

**Issue by CongSheng** [jeshraghian/snntorch#200]
* snntorch version: 0.6.1
* Python version: 3.10.9
* Operating System: Windows 10 Pro
* PyTorch version: 1.11.0

### Description
The recent MPS compatibility fix in `snntorch==0.6.1` seems to have issue which was traced back to snntorch/_neurons/neurons.py line 462. **"Attribute error: _SpikeTensor has no attribute 'is_mps'. did you mean 'is_mlc'?"** was raised during forward pass using `model(data)`. Reverting back to `snntorch==0.6.0` solved the issue. Maybe the documentation could be updated to set requirement for `PyTorch>=1.13.0` or some dependency fix can be implemented for MPS at neuron.py line 462.
```
def _SpikeTorchConv(*args, input_):
    ...
    elif arg.is_mps:
              arg = arg.to("cpu")
    ...
``` 

### What I Did
After constructing a spiking neural network such as the one in Tutorial 5, I ran a single iteration to test validity of the network:
`spk_rec, mem_rec = net(data)`. Issue is reproducible by using  `torch==1.11.0` instead of `torch==1.13.1` on the exact google Colab notebook for tutorial 5.

Full traceback obtained using Tutorial 5 while using `torch==1.11.0`.
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-17-7e073b45e7bb>](https://localhost:8080/#) in <module>
----> 1 spk_rec, mem_rec = net(data.view(batch_size, -1))
      2 print(mem_rec.size())

4 frames
[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

[<ipython-input-12-3a0d4c093035>](https://localhost:8080/#) in forward(self, x)
     22         for step in range(num_steps):
     23             cur1 = self.fc1(x)
---> 24             spk1, mem1 = self.lif1(cur1, mem1)
     25             cur2 = self.fc2(spk1)
     26             spk2, mem2 = self.lif2(cur2, mem2)

[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.9/dist-packages/snntorch/_neurons/leaky.py](https://localhost:8080/#) in forward(self, input_, mem)
    154 
    155         if hasattr(mem, "init_flag"):  # only triggered on first-pass
--> 156             mem = _SpikeTorchConv(mem, input_=input_)
    157         elif mem is False and hasattr(
    158             self.mem, "init_flag"

[/usr/local/lib/python3.9/dist-packages/snntorch/_neurons/neurons.py](https://localhost:8080/#) in _SpikeTorchConv(input_, *args)
    460         if arg.is_cuda:
    461             arg = arg.to("cpu")
--> 462         elif arg.is_mps:
    463             arg = arg.to("cpu")
    464         arg = torch.Tensor(arg)  # wash away the SpikeTensor class

AttributeError: '_SpikeTensor' object has no attribute 'is_mps'
```

**Comment by jeshraghian** [comment]
This is a good catch - thanks! 
Increasing the pytorch version requirement is a good idea, though might be painful to those stuck on old cuda versions.

One idea is to remove the if/elif statement and unconditionally put the tensor on CPU. 

I'll also check for a few other places where mps might throw an error, and I'll make things backwards compatible. 

Will comment here once I have a solution pushed!

**Comment by jetjodh** [comment]
Ran into the same issue.

**Comment by jeshraghian** [comment]
Just made a patch and have pushed it to PyPi. 
You won't need to update your PyTorch version for `snntorch==0.6.2` onwards.
Thanks again for flagging this!

**Comment by CongSheng** [comment]
Cool! Thank you for the speedy patch!
