### ISSUE TITLE
section 2.2 Overcoming the Dead Neuron Problem formals does not display correctly

### ISSUE THREAD

**Issue by khood5** [jeshraghian/snntorch#211]
* snntorch version:
* Python version:
* Operating System:

### Description

There is a bug in https://github.com/jeshraghian/snntorch/blob/master/docs/tutorials/tutorial_5.rst and how it is displayed on the website https://snntorch.readthedocs.io/en/latest/tutorials/tutorial_5.html

section 2.2 Overcoming the Dead Neuron Problem

on of the formals does not display correctly see screen shot

### What I Did

Just visit https://snntorch.readthedocs.io/en/latest/tutorials/tutorial_5.html and look under 2.2 Overcoming the Dead Neuron Problem

I am using firefox if that matters

![Screenshot 2023-04-26 at 13 46 52](https://user-images.githubusercontent.com/31542693/234660443-10fd4264-18d8-4a5b-b03f-e9ad807181d5.png)

**Comment by jeshraghian** [comment]
Thanks for the heads up! I just pushed a fix and it should compile within ~30 mins.
