### ISSUE TITLE
spikegen.delta issue

### ISSUE THREAD

**Issue by Taotaonoangry** [jeshraghian/snntorch#214]
In https://snntorch.readthedocs.io/en/latest/snntorch.spikegen.html#snntorch.spikegen.rate, the example for snntorch.spikegen.delta is incorrect. For example, given a = torch.Tensor([1, 2, 2.9, 3, 3.9]) and calling spikegen.delta(a, threshold=1)  return tensor([1., 1., 0., 0., 0.]), instead of the shown tensor([1., 1., 0., 1., 0.]).

Similarly, calling spikegen.delta(a, threshold=1, padding=True)  return tensor([0., 1., 0., 0., 0.]), instead of the shown tensor([0., 1., 0., 1., 0.]).

**Comment by jeshraghian** [comment]
Thanks for catching this. Docstrings have been fixed now.
