### ISSUE TITLE
Bug: I don't find self.R and self.C in snntorch/snntorch/_neurons /lapicque.py

### ISSUE THREAD

**Issue by Wang-XR** [jeshraghian/snntorch#257]
I don't find self.timestep, self.R and self.C in snntorch/snntorch/_neurons /lapicque.py
In function _base_state_function of the class LIF, the self.timestep, self.R and self.C are used, but they are not defined in this class and its father class. In addition, self.reset is not a bool variable.
![image](https://github.com/jeshraghian/snntorch/assets/82993367/deae7395-e7a0-4052-b60f-bfab3d4892fc)
![image](https://github.com/jeshraghian/snntorch/assets/82993367/49b165be-2faf-4165-9d93-5e087d6bca7f)
![af64105809c0d5d3a26ffcb71ea44e8](https://github.com/jeshraghian/snntorch/assets/82993367/accfc04c-6f59-47dd-b4d4-8fd9e5965a18)
The formula provided is inconsistent with the code.

**Comment by jeshraghian** [comment]
Please share a minimal working example of what you are attempting to do.

**Comment by ahenkes1** [comment]
@Wang-XR any updates?
