### ISSUE TITLE
The time step in Tutorial 5

### ISSUE THREAD

**Issue by Whale-xh** [jeshraghian/snntorch#283]
Hello,
The training step num_steps of the training network in Tutorial 5 is 25, what is the time between each step? Is it possible to customize the settings?What is the unit of time?

**Comment by Moerai** [comment]
I think the SNN is using num_steps to train, just like a traditional ANN uses epochs to train.

**Comment by Moerai** [comment]
There is no unit for num_steps. This is similar to the epoch used by ANNs, and can be customized by scaling num_steps.
