### ISSUE TITLE
Repalce "torch._six.string_classes" with "str" in neuromorphic_dataset.py

### ISSUE THREAD

**Issue by githubofaliyev** [jeshraghian/snntorch#284]
Since Pytorch dropped support for _six module, the line https://github.com/jeshraghian/snntorch/blob/bf763fdf5138e976b085a700cc12e6ec3f5d1a44/snntorch/spikevision/neuromorphic_dataset.py#L145C9-L145C56 throws erro with the latest Torch and Python versions.

**Comment by jeshraghian** [comment]
The datasets module has been deprecated, as Tonic is a far more useful dataloader.
