### ISSUE TITLE
'snntorch' has no attribute 'FastSigmoid'

### ISSUE THREAD

**Issue by Dola47** [jeshraghian/snntorch#32]
* snntorch version: 0.2.8
* Python version: 2.7.5
* Operating System: Windows 10

### Description
I tried to use the surrogate gradient function by running the following line of code: 
```
spike_grad = snn.FastSigmoid.apply
```
However, I am getting an error stating that "module 'snntorch' has no attribute 'FastSigmoid'". 

I see that it is not implemented yet to the neuron models in your __init__.py file, may I ask when the push is going to be done?

Moreover, I see that we have only examples of applying rate encoding to the MNIST dataset, I need to ask if it is possible to have an example showing how to use the Latency encoding may also be on a Convolution network?

Thanks in advance.

**Comment by vinniesun** [comment]
Hi Dola47,

Please use the code below to call the FastSigmoid function

`
from snntorch import surrogate

spike_grad = surrogate.FastSigmoid.apply
`
