### ISSUE TITLE
The examples in Colab is out of date

### ISSUE THREAD

**Issue by icarusunimelb** [jeshraghian/snntorch#49]
### Description

The tutorial_1 code in Colab looks like based on an out-of-date snntorch version. 

For example, the code of rate encoding in Colab is 
```
spike_data, spike_targets = spikegen.rate(data_it, targets_it, num_outputs=num_outputs, num_steps=num_steps,
                                          gain=1, offset=0, one_hot=False, time_varying_targets=False)
```
While the up-to-date code in Github is 
```
spike_data = spikegen.rate(data_it, num_steps=num_steps, gain=1, offset=0). 
```
As I tried, both from this link https://snntorch.readthedocs.io/en/latest/examples.html and clicking the open in colab icon will lead to the wrong version tutorials. 

### Solution

A quick solution is directly cloning the repository and running locally or loading the notebook to Colab via Github link according to https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb#:~:text=Colab%20can%20load%20public%20github,with%20no%20required%20authorization%20step.

**Comment by jeshraghian** [comment]
Thanks for catching this! I have updated the Colab hyperlinks to point to the correct tutorials in master.
