### ISSUE TITLE
About using NMNIST dataset, num_steps=300, dt=1000 

### ISSUE THREAD

**Issue by asselkembay** [jeshraghian/snntorch#56]
Good day!

I wanted to know what does mean num_steps = 300. Does it mean that to use only 300 events?
Like we have 60000 samples in NMNIST, and each sample has around 4500 events. But if we set dt =1000,
and num_steps = 300, so we use only 300 events out of 4500?

Thank you!

**Comment by jeshraghian** [comment]
Hi @asselkembay! 

`num_steps` refers to the number of time steps being simulated, and `dt` is the integration window of the events in microseconds.

In a recurrent neural network, the number of steps corresponds to the length of the input sequence. You can change the sequence length of the input using `num_steps`. 

The NMNIST dataset was filmed using a DVS Camera which generates a variable number of events at any time step.
If `dt=1`, then your input would catch very few events at each time step. 
If `dt=1000`, then you are passing in many more (1ms worth) events at each time step. 

As you increase `dt`, the faster the NMNIST will be passed into the neural network.
This means that for a fixed `num_steps`, the final steps will have no more events. 
The default values are widely used amongst papers.

I recommend opening up this notebook, playing with the values, and visualizing them to see how they are related:
https://github.com/jeshraghian/snntorch/blob/master/examples/NMNIST.ipynb
