### ISSUE TITLE
A problem occurred when running the code in tutorial 2

### ISSUE THREAD

**Issue by EliteSasuke** [jeshraghian/snntorch#67]
* snntorch version:0.4.4
* Python version:3.8
* Operating System:Windows 10

### Description
Hello Jason,
When I ran the code in Tutorial 2, I found that several ploting functions were undefined. Can you tell me which package they are included in so that I can install the missing package？
Looking forward to your reply.

Thanks,
Sasuke

### What I Did

![Screenshot 2021-10-03 221152](https://user-images.githubusercontent.com/86088706/135757610-bfc4eeba-b07e-4acb-8cc8-077ad5e1bf61.png)
![Screenshot 2021-10-03 221222](https://user-images.githubusercontent.com/86088706/135757615-250dfd13-c3ad-4f75-8067-079069d10f62.png)
![Screenshot 2021-10-03 221323](https://user-images.githubusercontent.com/86088706/135757619-3977832f-3acf-4977-9084-6cb09f0e6624.png)

**Comment by jeshraghian** [comment]
Hi Sasuke,

Make sure you run the "Plotting Settings" code-block (bottom of the attached image).
That contains all of the code related to plotting figures.
Please let me know if that solves your issue, and I can update the tutorials so people don't miss it in the future!

Thanks,
Jason

![image](https://user-images.githubusercontent.com/40262130/135771295-e1fe00bb-d593-4e13-b282-c0abff66fb84.png)

**Comment by EliteSasuke** [comment]
Thank you very much for solving my problem.Since I used pycharm instead of colab before, I did not realize the existence of "plotting settings"code-block.
