### ISSUE TITLE
URL Fix in tutorial 6

### ISSUE THREAD

**Issue by MrPeterJin** [jeshraghian/snntorch#76]
* snntorch version: 0.4.11
* Python version: 3.9
* Operating System: Windows 11

### Description

While I am looking through your tutorials, I have noticed that in tutorial 6, the following line:

> Part of this tutorial was inspired by Friedemann Zenke’s extensive work on SNNs. Check out his repo on surrogate gradients here, and a favourite paper...

seems to have an unresolved URL `https://github.corm/fzenke/spytorch`, which I think 'corm' is misspelled.

### What I Did

Click the link.

**Comment by jeshraghian** [comment]
Thanks for finding this issue! URL is now fixed.
