### ISSUE TITLE
RSynaptic Neuron Model NOT in snnTorch 

### ISSUE THREAD

**Issue by msbouanane** [jeshraghian/snntorch#87]
Hello, 
I am trying to use the RSynaptic neuron model but even though it is documented in the snnTorch website, the `class RSynaptic(LIF)` is not included in the `snntroch` module. 
This this the error I get when I try to use it: 
> AttributeError: module 'snntorch' has no attribute 'RSynaptic'

**Comment by jeshraghian** [comment]
I'm still testing their robustness, so I have not yet pushed the latest neurons to pypi (i.e., not yet installable via `pip install ...`). 
I'll have this finalised in the week, but until then, you will need to install snntorch from source:

```
$ git clone https://github.com/jeshraghian/snnTorch
$ cd snnTorch
$ python setup.py install
```

**Comment by jeshraghian** [comment]
I've pushed all the latest updates to PyPi and the `RSynaptic(LIF)` neuron model should now work correctly.

**Comment by msbouanane** [comment]
It does work correctly! Thanks a lot.
